### ISSUE TITLE
I run the example and get following error

### ISSUE THREAD

**Issue by l1t1** [Aliuyanfeng/wkhtmltopdf-example#1]
I edit the code as some method and file missing
```
import json
import platform
import time

import pdfkit



class PDFExportUtil(object):

    def start_export(self):
        """导出报告"""

        # 字典存储pdf映射数据
        result = dict()

        file_path = f"./template/report.js"
        insert_data = f"""
            var reportJsonData = {json.dumps(result, indent=4, ensure_ascii=False)}
        """.strip()
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(insert_data)
        self.html_to_pdf()

    def html_to_pdf(self):
        """html 转 pdf"""
        # 启动参数
        wkhtmltopdf_options = {
            'enable-local-file-access': '--enable-local-file-access',
            'encoding': "utf-8",
            'javascript-delay': '10000',
            'header-left': '报告-[date] [time]',
            'header-font-size': 8,
            'header-spacing': 5,
            'footer-center': '第[page] / [topage]页',
            'footer-font-size': 8,
            'margin-top': 10,
            'dpi': 300
        }
        # 下载的wkhtmltopdf绝对路径，修改为自己存放的位置
        if platform.system() == 'Linux':
            path_wkthmltopdf = r"/usr/local/wkhtmltox/bin/wkhtmltopdf"
        else:
            path_wkthmltopdf = r'E:\wkhtmltox\bin\wkhtmltopdf.exe'                                 #---my dir

        config = pdfkit.configuration(wkhtmltopdf=path_wkthmltopdf)

        # html 输入 out.pdf 输出
        cur_time = time.strftime('%Y%m%d%H%M%S', time.localtime(time.time()))
        out_path = f"./file/report/报告({cur_time}).pdf"
        pdfkit.from_file("./template/example.html", out_path, configuration=config,        #---- no index.html found
                         options=wkhtmltopdf_options)
        return True
        """更新报告路径"""
        params = {
            "id": r_id,
            "report_path": r_path
        }
        sql = """
            update t_report_export set report_path = %(report_path)s where id = %(id)s
        """
        self.pg_conn.execute(sql, params)
        self.pg_conn.commit()


a=PDFExportUtil()          # -----------------------I guess
a.start_export()             # -----------------------I guess

```
results
```
D:\wkhtmltopdf-example-main>python ReportExportUtil.py
Traceback (most recent call last):
  File "ReportExportUtil.py", line 67, in <module>
    a.start_export()
  File "ReportExportUtil.py", line 23, in start_export
    self.html_to_pdf()
  File "ReportExportUtil.py", line 51, in html_to_pdf
    pdfkit.from_file("./template/example.html", out_path, configuration=config,
  File "D:\Python38\lib\site-packages\pdfkit\api.py", line 51, in from_file
    return r.to_pdf(output_path)
  File "D:\Python38\lib\site-packages\pdfkit\pdfkit.py", line 201, in to_pdf
    self.handle_error(exit_code, stderr)
  File "D:\Python38\lib\site-packages\pdfkit\pdfkit.py", line 158, in handle_error
    raise IOError("wkhtmltopdf exited with non-zero code {0}. error:\n{1}".format(exit_code, error_msg))
OSError: wkhtmltopdf exited with non-zero code 1. error:
QPainter::begin(): Returned false
Exit with code 1, due to unknown error.
```

**Comment by Aliuyanfeng** [comment]
What platform do you have to run on，and have you installed wkhtmltopdf？🧐

**Comment by l1t1** [comment]
I installed wkhtmltopdf to E:\wkhtmltox 
in Windows 7

**Comment by Aliuyanfeng** [comment]
> I installed wkhtmltopdf to E:\wkhtmltox in Windows 7

Is the path correct?  you installed path should is path_wkthmltopdf = r 'e :\wkhtmltox\bin\wkhtmltopdf.exe'

**Comment by Aliuyanfeng** [comment]
> OSError: wkhtmltopdf exited with non-zero code 1. error:
> QPainter::begin(): Returned false
> Exit with code 1, due to unknown error.

Please check for file path problems (no folder, illegal characters in file name, etc.)
File opening

**Comment by l1t1** [comment]
I try run the binary file and got follwing , the output example_html.pdf is generated as attchment
```
D:\>e:\wkhtmltox\bin\wkhtmltopdf D:\wkhtmltopdf-example-main\./template/example.html example_html.pdf
Loading pages (1/6)
Warning: Blocked access to file D:/wkhtmltopdf-example-main/template/static/css/index.css
Warning: Blocked access to file D:/wkhtmltopdf-example-main/template/static/js/vue@2.7.15.js
Warning: Blocked access to file D:/wkhtmltopdf-example-main/template/static/js/echarts.js
Warning: Blocked access to file D:/wkhtmltopdf-example-main/template/report.js
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ProtocolUnknownError
```

**Comment by l1t1** [comment]
[example_html.pdf](https://github.com/user-attachments/files/16971545/example_html.pdf)
the file can be opened.

**Comment by Aliuyanfeng** [comment]
> I try run the binary file and got follwing , the output example_html.pdf is generated as attchment
> 
> ```
> D:\>e:\wkhtmltox\bin\wkhtmltopdf D:\wkhtmltopdf-example-main\./template/example.html example_html.pdf
> Loading pages (1/6)
> Warning: Blocked access to file D:/wkhtmltopdf-example-main/template/static/css/index.css
> Warning: Blocked access to file D:/wkhtmltopdf-example-main/template/static/js/vue@2.7.15.js
> Warning: Blocked access to file D:/wkhtmltopdf-example-main/template/static/js/echarts.js
> Warning: Blocked access to file D:/wkhtmltopdf-example-main/template/report.js
> Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
> Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
> Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
> Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown
> Counting pages (2/6)
> Resolving links (4/6)
> Loading headers and footers (5/6)
> Printing pages (6/6)
> Done
> Exit with code 1 due to network error: ProtocolUnknownError
> ```
I haven't tested it on windows7, I'm running windows10 and Linux，In terms of errors, most are caused by routing problems or coding problems，I'm sorry I couldn't help you
